from pathlib import Path


DATA_DIRECTORY = Path("data")
ARTICLES_DIRECTORY = Path(DATA_DIRECTORY / "articles")
WORDCLOUDS_DIRECTORY = Path(DATA_DIRECTORY / "WordClouds")
PATHS_TO_CREATE_DIRECTORIES = [
    DATA_DIRECTORY,
    ARTICLES_DIRECTORY,
    WORDCLOUDS_DIRECTORY
]

FILE_SUFFIX = ".json"
